---
- name: Ping Test Playbook
  hosts: localhost
  become: true # Elevate privileges to sudo / root on the target host
  gather_facts: false
  vars:
    delegate_host: ansible-ubuntu-1.drewz.local

  roles:
    - ping_test
