---
- name: Write JSON file
  hosts: localhost
  tasks:
    - name: Write simple JSON content to a file
      copy:
        content: |
          {
            "key": "value"
          }
        dest: "/tmp/simple-test-inside-pod.json"
