---
- name: Ping google.com from a specific host
  command: ping -c4 google.com
  delegate_to: "{{ delegate_host }}"  # Delegates the task to be executed on the Ansible host via Ansible Core, *not* inside the K8s pod!
  register: ping_result

- name: Print ping results
  debug:
    msg: "{{ ping_result.stdout_lines }}"
